### PR TITLE
Replace Strings with Text, isolate base types/classes from client/server code

### PR DESCRIPTION
**Pull request by SX91**
This change is [Reviewable](https://reviewable.io/reviews/toktok/hs-msgpack-rpc/5)

### CODE REVIEW

**Comment by iphydf** [comment]
Review status: 0 of 14 files reviewed at latest revision, 4 unresolved discussions.

---

_[network-msgpack-rpc.cabal, line 58 at r1](https://reviewable.io:443/reviews/toktok/hs-msgpack-rpc/5#-KWzSXgbiSzqVmc6_Ki1:-KWzSXgbiSzqVmc6_Ki2:bonpi1c) ([raw file](https://github.com/toktok/hs-msgpack-rpc/blob/c71043c3e9b5713447e1cd60e6289f212ef67e06/network-msgpack-rpc.cabal#L58)):_

> ```
>     , conduit
>     , conduit-extra
>     , data-default-class >= 0.1.2
> ```

We don't really need a recent version of this package. We're fine with 0.0.1, but then we need to include data-default-instances-base. I'd prefer we do that.

---

_[src/Network/MessagePack/Capabilities.hs, line 21 at r1](https://reviewable.io:443/reviews/toktok/hs-msgpack-rpc/5#-KWzQx8PoTHgQ8pE_ceT:-KWzQx8PoTHgQ8pE_ceU:b7meota) ([raw file](https://github.com/toktok/hs-msgpack-rpc/blob/c71043c3e9b5713447e1cd60e6289f212ef67e06/src/Network/MessagePack/Capabilities.hs#L21)):_

> ``` Haskell
> 
> instance MessagePack ServerCapability
> instance Default ServerCapability
> ```

What is the default ServerCapability? Why is this needed? The default server capability list is the empty list.

---

_[src/Network/MessagePack/Rpc.hs, line 55 at r1](https://reviewable.io:443/reviews/toktok/hs-msgpack-rpc/5#-KWzRhfz0n7PkYsMv5iq:-KWzRhfz0n7PkYsMv5ir:b7newxb) ([raw file](https://github.com/toktok/hs-msgpack-rpc/blob/c71043c3e9b5713447e1cd60e6289f212ef67e06/src/Network/MessagePack/Rpc.hs#L55)):_

> ``` Haskell
>   {-# INLINE method #-}
>   docs r = (Server.methodName $ method r, I.docs $ intfPure r)
>   {-# INLINE docs #-}
> ```

Why is docs now marked as inline? Getting method docs is very unlikely to be performance sensitive. Have you measured any performance improvements with all the added pragmas?

---

_[src/Network/MessagePack/Types/Client.hs, line 2 at r1](https://reviewable.io:443/reviews/toktok/hs-msgpack-rpc/5#-KWzSFaQOjK_CPCuPCcA:-KWzSFaQOjK_CPCuPCcB:b-p88uh1) ([raw file](https://github.com/toktok/hs-msgpack-rpc/blob/c71043c3e9b5713447e1cd60e6289f212ef67e06/src/Network/MessagePack/Types/Client.hs#L2)):_

> ``` Haskell
> module Network.MessagePack.Types.Client
>   ( RpcType(..)
> ```

Can you add a space before `(..)` in all the export lists?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/hs-msgpack-rpc/5)_

**Comment by iphydf** [comment]
@SX91 can you rebase this? I've added data-default-instances-base, so the newer version of data-default is no longer necessary.

**Comment by SX91** [comment]
@iphydf rebased.

**Comment by iphydf** [comment]
Thanks. Why did you expose more modules? Do you have a use case for each of them? If so, we need tests displaying those use cases. If not, I'd like to be conservative with that, because (theoretically), once exposed you can never make it private again, so we're locked down to the names we created now.

**Comment by iphydf** [comment]
I'd like to merge this without the change in module exposure list. Can you make a separate PR for that commit, so we can discuss it there, and it doesn't block the Text changes?

**Comment by SX91** [comment]
@iphydf Done. Except that `Types` is exposed too.

**Comment by iphydf** [comment]
:lgtm: 

---

Review status: 0 of 14 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/hs-msgpack-rpc/5#-:-KYwu16t8mohYxeToBMT:bg7igkv)*

**Pull request merged**
