### PR TITLE
fix: Fix MonadFail conditional instance

### PR DESCRIPTION
**Pull request by jimenezrick**
I think it should be like this, right?

---
This change is [Reviewable](https://reviewable.io/reviews/toktok/hs-msgpack-rpc-conduit/41)

### CODE REVIEW

**Review by iphydf — APPROVED** [review]
Yes, this is correct, thanks!

**Comment by iphydf** [comment]
Do you want to sign your commit? Otherwise I can amend and sign it.

**Comment by jimenezrick** [comment]
Done.

**Comment by iphydf** [comment]
I meant GPG sign. I've done that now :) I'll merge once CI passes again. Thanks!

**Pull request merged**
